#!/bin/bash

# shellcheck disable=SC2034
archlinux-latest-base() {
    declare -a default_global_args_array=(
        
    )

    local name
    name="$(generate-unique-name-base)"
    declare -a default_args_array=(
        --name="$name"
        --hostname="$name"
        --pull=newer
    )

    local image="docker.io/library/archlinux:latest"

    podman-run "$@"
}

archlinux-latest() { ct rm tty archlinux-latest-base "$@"; }
