#!/bin/bash

# shellcheck disable=SC2086
# shellcheck disable=SC2154
t-network-host() {
    local self="${FUNCNAME[0]}"

    # Check if the function already ran
    if is-toggle-toggled "$self"; then
        # Execute the remaining arguments and return success when done
        "$@"
        return
    fi

    # Check for conflicts
    if is-toggle-toggled t-network-none; then
        echo "'t-network-host' is incompatible with 't-network-none'"
        return 1
    fi

    # Add the function name the to the toggled array
    toggled_array+=("$self")
    # Add the arguments name the to the extra args array
    extra_args_array+=(--network=host)

    # Execute the remaining arguments
    "$@"
}

t-network-none() {
    local self="${FUNCNAME[0]}"

    # Check if the function already ran
    if is-toggle-toggled "$self"; then
        # Execute the remaining arguments and return success when done
        "$@"
        return
    fi

    # Check for conflicts
    if is-toggle-toggled t-network-none; then
        echo "'t-network-host' is incompatible with 't-network-none'"
        return 1
    fi

    # Add the function name the to the toggled array
    toggled_array+=("$self")
    # Add the arguments name the to the extra args array
    extra_args_array+=(--network=none)

    # Execute the remaining arguments
    "$@"
}
