#!/bin/bash

# shellcheck disable=SC2086
# shellcheck disable=SC2154
t-security-opt-label-disable() {
    local self="${FUNCNAME[0]}"

    # Check if the function already ran
    if is-toggle-toggled "t-privileged" || is-toggle-toggled "$self"; then
        # Execute the remaining arguments and return success when done
        "$@"
        return
    fi

    # Add the function name the to the toggled array
    toggled_array+=("$self")
    # Add the arguments name the to the extra args array
    extra_args_array+=(--security-opt=label=disable)

    # Execute the remaining arguments
    "$@"
}


t-security-opt-seccomp-unconfined() {
    local self="${FUNCNAME[0]}"

    # Check if the function already ran
    if is-toggle-toggled "t-privileged" || is-toggle-toggled "$self"; then
        # Execute the remaining arguments and return success when done
        "$@"
        return
    fi

    # Add the function name the to the toggled array
    toggled_array+=("$self")
    # Add the arguments name the to the extra args array
    extra_args_array+=(--security-opt=seccomp=unconfined)

    # Execute the remaining arguments
    "$@"
}

t-security-opt-unmask-all() {
    local self="${FUNCNAME[0]}"

    # Check if the function already ran
    if is-toggle-toggled "t-privileged" || is-toggle-toggled "$self"; then
        # Execute the remaining arguments and return success when done
        "$@"
        return
    fi

    # Add the function name the to the toggled array
    toggled_array+=("$self")
    # Add the arguments name the to the extra args array
    extra_args_array+=(--security-opt=unmask=ALL)

    # Execute the remaining arguments
    "$@"
}

t-security-opt-apparmor-unconfined() {
    local self="${FUNCNAME[0]}"

    # Check if the function already ran
    if is-toggle-toggled "t-privileged" || is-toggle-toggled "$self"; then
        # Execute the remaining arguments and return success when done
        "$@"
        return
    fi

    # Add the function name the to the toggled array
    toggled_array+=("$self")
    # Add the arguments name the to the extra args array
    extra_args_array+=(--security-opt=apparmor=unconfined)

    # Execute the remaining arguments
    "$@"
}

t-security-opt-type-container-runtime-t() {
    local self="${FUNCNAME[0]}"

    # Check if the function already ran
    if is-toggle-toggled "t-privileged" || is-toggle-toggled "$self"; then
        # Execute the remaining arguments and return success when done
        "$@"
        return
    fi

    # Add the function name the to the toggled array
    toggled_array+=("$self")
    # Add the arguments name the to the extra args array
    extra_args_array+=(--security-opt=label=type:container_runtime_t)

    # Execute the remaining arguments
    "$@"
}